#pragma once

#include <zmq.h>

// if anything is missing, please add it here

namespace zq {

  enum class CtxOptionName : int {
    IO_THREADS = ZMQ_IO_THREADS,
    MAX_SOCKETS = ZMQ_MAX_SOCKETS,
    SOCKET_LIMIT = ZMQ_SOCKET_LIMIT,
    THREAD_PRIORITY = ZMQ_THREAD_PRIORITY,
    THREAD_SCHED_POLICY = ZMQ_THREAD_SCHED_POLICY,
    MAX_MSGSZ = ZMQ_MAX_MSGSZ,
    MSG_T_SIZE = ZMQ_MSG_T_SIZE,
    THREAD_AFFINITY_CPU_ADD = ZMQ_THREAD_AFFINITY_CPU_ADD,
    THREAD_AFFINITY_CPU_REMOVE = ZMQ_THREAD_AFFINITY_CPU_REMOVE,
    THREAD_NAME_PREFIX = ZMQ_THREAD_NAME_PREFIX,
    IPV6 = ZMQ_IPV6,
    BLOCKY = ZMQ_BLOCKY
  };



  enum class SocketType : int
  {
    REQ = ZMQ_REQ,
    REP = ZMQ_REP,
    DEALER = ZMQ_DEALER,
    ROUTER = ZMQ_ROUTER,
    PUB = ZMQ_PUB,
    SUB = ZMQ_SUB,
    XPUB = ZMQ_XPUB,
    XSUB = ZMQ_XSUB,
    PUSH = ZMQ_PUSH,
    PULL = ZMQ_PULL,
    PAIR = ZMQ_PAIR,
    STREAM = ZMQ_STREAM
  };


  enum class SocketOptionName : int {
    AFFINITY = ZMQ_AFFINITY,
    IDENTITY = ZMQ_IDENTITY,
    SUBSCRIBE = ZMQ_SUBSCRIBE,
    UNSUBSCRIBE = ZMQ_UNSUBSCRIBE,
    RATE = ZMQ_RATE,
    RECOVERY_IVL = ZMQ_RECOVERY_IVL,
    SNDBUF = ZMQ_SNDBUF,
    RCVBUF = ZMQ_RCVBUF,
    RCVMORE = ZMQ_RCVMORE,
    FD = ZMQ_FD,
    EVENTS = ZMQ_EVENTS,
    TYPE = ZMQ_TYPE,
    LINGER = ZMQ_LINGER,
    RECONNECT_IVL = ZMQ_RECONNECT_IVL,
    BACKLOG = ZMQ_BACKLOG,
    RECONNECT_IVL_MAX = ZMQ_RECONNECT_IVL_MAX,
    MAXMSGSIZE = ZMQ_MAXMSGSIZE,
    SNDHWM = ZMQ_SNDHWM,
    RCVHWM = ZMQ_RCVHWM,
    MULTICAST_HOPS = ZMQ_MULTICAST_HOPS,
    RCVTIMEO = ZMQ_RCVTIMEO,
    SNDTIMEO = ZMQ_SNDTIMEO,
    LAST_ENDPOINT = ZMQ_LAST_ENDPOINT,
    ROUTER_MANDATORY = ZMQ_ROUTER_MANDATORY,
    TCP_KEEPALIVE = ZMQ_TCP_KEEPALIVE,
    TCP_KEEPALIVE_CNT = ZMQ_TCP_KEEPALIVE_CNT,
    TCP_KEEPALIVE_IDLE = ZMQ_TCP_KEEPALIVE_IDLE,
    TCP_KEEPALIVE_INTVL = ZMQ_TCP_KEEPALIVE_INTVL,
    TCP_ACCEPT_FILTER = ZMQ_TCP_ACCEPT_FILTER,
    IMMEDIATE = ZMQ_IMMEDIATE,
    XPUB_VERBOSE = ZMQ_XPUB_VERBOSE,
    ROUTER_RAW = ZMQ_ROUTER_RAW,
    IPV6 = ZMQ_IPV6,
    MECHANISM = ZMQ_MECHANISM,
    PLAIN_SERVER = ZMQ_PLAIN_SERVER,
    PLAIN_USERNAME = ZMQ_PLAIN_USERNAME,
    PLAIN_PASSWORD = ZMQ_PLAIN_PASSWORD,
    CURVE_SERVER = ZMQ_CURVE_SERVER,
    CURVE_PUBLICKEY = ZMQ_CURVE_PUBLICKEY,
    CURVE_SECRETKEY = ZMQ_CURVE_SECRETKEY,
    CURVE_SERVERKEY = ZMQ_CURVE_SERVERKEY,
    PROBE_ROUTER = ZMQ_PROBE_ROUTER
  };

  enum class SendFlags : int {
    NONE = 0,
    SNDMORE = ZMQ_SNDMORE
  };
}
